-- VHDL Entity ece411.CacheWay.symbol
--
-- Created:
--          by - chachon2.ews (linux-a2.ews.illinois.edu)
--          at - 16:50:14 08/04/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY CacheWay IS
   PORT( 
      CacheWayDataIN : IN     LC3B_OWORD;
      CacheWayWrite  : IN     std_logic;
      DirtyIN        : IN     std_logic;
      DirtyWrite     : IN     std_logic;
      INDEX          : IN     LC3B_C_INDEX;
      RESET_L        : IN     std_logic;
      Tag            : IN     LC3B_C_TAG;
      TagWrite       : IN     std_logic;
      CacheLine      : OUT    LC3B_OWORD;
      CacheTag       : OUT    LC3B_C_TAG;
      Dirty          : OUT    std_logic;
      Valid          : OUT    std_logic
   );

-- Declarations

END CacheWay ;

--
-- VHDL Architecture ece411.CacheWay.struct
--
-- Created:
--          by - chachon2.ews (linux-a2.ews.illinois.edu)
--          at - 16:50:14 08/04/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF CacheWay IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT DataArray
   PORT (
      CacheWayDataIN : IN     LC3B_OWORD ;
      CacheWayWrite  : IN     std_logic ;
      INDEX          : IN     LC3B_C_INDEX ;
      RESET_L        : IN     std_logic ;
      CacheLine      : OUT    LC3B_OWORD 
   );
   END COMPONENT;
   COMPONENT DirtyArray
   PORT (
      DirtyIN    : IN     std_logic ;
      DirtyWrite : IN     std_logic ;
      INDEX      : IN     LC3B_C_INDEX ;
      RESET_L    : IN     std_logic ;
      Dirty      : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT TagArray
   PORT (
      INDEX    : IN     LC3B_C_INDEX ;
      RESET_L  : IN     std_logic ;
      Tag      : IN     LC3B_C_TAG ;
      TagWrite : IN     std_logic ;
      CacheTag : OUT    LC3B_C_TAG 
   );
   END COMPONENT;
   COMPONENT ValidArray
   PORT (
      CacheWayWrite : IN     std_logic ;
      INDEX         : IN     LC3B_C_INDEX ;
      RESET_L       : IN     std_logic ;
      Valid         : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DataArray USE ENTITY ece411.DataArray;
   FOR ALL : DirtyArray USE ENTITY ece411.DirtyArray;
   FOR ALL : TagArray USE ENTITY ece411.TagArray;
   FOR ALL : ValidArray USE ENTITY ece411.ValidArray;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   aDataArray : DataArray
      PORT MAP (
         CacheWayDataIN => CacheWayDataIN,
         CacheWayWrite  => CacheWayWrite,
         INDEX          => INDEX,
         RESET_L        => RESET_L,
         CacheLine      => CacheLine
      );
   aDirtyArray : DirtyArray
      PORT MAP (
         DirtyIN    => DirtyIN,
         DirtyWrite => DirtyWrite,
         INDEX      => INDEX,
         RESET_L    => RESET_L,
         Dirty      => Dirty
      );
   aTagArray : TagArray
      PORT MAP (
         INDEX    => INDEX,
         RESET_L  => RESET_L,
         Tag      => Tag,
         TagWrite => TagWrite,
         CacheTag => CacheTag
      );
   aValidArray : ValidArray
      PORT MAP (
         CacheWayWrite => CacheWayWrite,
         INDEX         => INDEX,
         RESET_L       => RESET_L,
         Valid         => Valid
      );

END struct;
