-- VHDL Entity ece411.mp2_CPU.symbol
--
-- Created:
--          by - chachon2.ews (linux-a1.ews.illinois.edu)
--          at - 15:26:04 06/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY mp2_CPU IS
   PORT( 
      RESET_L : IN     std_logic;
      START_H : IN     std_logic
   );

-- Declarations

END mp2_CPU ;

--
-- VHDL Architecture ece411.mp2_CPU.struct
--
-- Created:
--          by - chachon2.ews (linux-a1.ews.illinois.edu)
--          at - 15:26:04 06/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;


ARCHITECTURE struct OF mp2_CPU IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ADDRESS        : LC3b_word;
   SIGNAL ALUMuxSel      : std_logic;
   SIGNAL ALUop          : LC3b_aluop;
   SIGNAL B              : LC3b_word;
   SIGNAL CheckN         : std_logic;
   SIGNAL CheckP         : std_logic;
   SIGNAL CheckZ         : std_logic;
   SIGNAL D              : LC3b_word;           -- := '1';
   SIGNAL DATAIN         : LC3b_word;
   SIGNAL DATAOUT        : LC3b_word;
   SIGNAL DR             : LC3b_word;
   SIGNAL F1             : LC3b_word;
   SIGNAL JSR_R          : std_logic;
   SIGNAL LBD_STBMux2Sel : std_logic;
   SIGNAL LDB_STBMuxSel  : std_logic;
   SIGNAL LEAMuxSel      : std_logic;
   SIGNAL LoadIR         : std_logic;
   SIGNAL LoadMAR        : std_logic;
   SIGNAL LoadMDR        : std_logic;
   SIGNAL LoadNZP        : std_logic;
   SIGNAL LoadPC         : std_logic;
   SIGNAL MARMuxSel      : std_logic;
   SIGNAL MDRMuxSel      : std_logic;
   SIGNAL MREAD_L        : std_logic;
   SIGNAL MRESP_H        : std_logic;
   SIGNAL MWRITEH_L      : std_logic;
   SIGNAL MWRITEL_L      : std_logic;
   SIGNAL OpImmBit       : std_logic;
   SIGNAL Opcode         : LC3b_opcode;
   SIGNAL PCMuxSel       : LC3B_4MUX_SEL;
   SIGNAL PCPlus2out     : LC3b_word;           -- PCPlus2out
   SIGNAL RFMuxSel       : std_logic;
   SIGNAL RegMuxSel      : std_logic;           -- RegMuxSel
   SIGNAL RegWrite       : std_logic;
   SIGNAL ShiftAD        : LC3B_SHFTOP;
   SIGNAL ShiftOpSel     : std_logic;
   SIGNAL StoreSR        : std_logic;
   SIGNAL Trap_JSRMuxSel : std_logic;
   SIGNAL clk            : std_logic := '0';
   SIGNAL dest1          : LC3b_Reg;
   SIGNAL dest2          : LC3b_word;
   SIGNAL n              : std_logic;
   SIGNAL p              : std_logic;
   SIGNAL sig0           : std_logic;
   SIGNAL z              : std_logic;


   -- Component Declarations
   COMPONENT CLKgen
   PORT (
      clk : INOUT  std_logic  := '0'
   );
   END COMPONENT;
   COMPONENT Control
   PORT (
      CheckN         : IN     std_logic ;
      CheckP         : IN     std_logic ;
      CheckZ         : IN     std_logic ;
      JSR_R          : IN     std_logic ;
      MRESP_H        : IN     std_logic ;
      OpImmBit       : IN     std_logic ;
      Opcode         : IN     LC3b_opcode ;
      RESET_L        : IN     std_logic ;
      START_H        : IN     std_logic ;
      ShiftAD        : IN     LC3B_SHFTOP ;
      clk            : IN     std_logic ;
      n              : IN     std_logic ;
      p              : IN     std_logic ;
      z              : IN     std_logic ;
      ALUMuxSel      : OUT    std_logic ;
      ALUop          : OUT    LC3b_aluop ;
      LBD_STBMux2Sel : OUT    std_logic ;
      LDB_STBMuxSel  : OUT    std_logic ;
      LEAMuxSel      : OUT    std_logic ;
      LoadIR         : OUT    std_logic ;
      LoadMAR        : OUT    std_logic ;
      LoadMDR        : OUT    std_logic ;
      LoadNZP        : OUT    std_logic ;
      LoadPC         : OUT    std_logic ;
      MARMuxSel      : OUT    std_logic ;
      MDRMuxSel      : OUT    std_logic ;
      MREAD_L        : OUT    std_logic ;
      MWRITEH_L      : OUT    std_logic ;
      MWRITEL_L      : OUT    std_logic ;
      PCMuxSel       : OUT    LC3B_4MUX_SEL ;
      RFMuxSel       : OUT    std_logic ;
      RegMuxSel      : OUT    std_logic ;
      RegWrite       : OUT    std_logic ;
      ShiftOpSel     : OUT    std_logic ;
      StoreSR        : OUT    std_logic ;
      Trap_JSRMuxSel : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT DRAMAuditor
   PORT (
      ADDRESS   : IN     LC3b_word ;
      MREAD_L   : IN     std_logic ;
      MWRITEH_L : IN     std_logic ;
      MWRITEL_L : IN     std_logic ;
      RESET_L   : IN     std_logic 
   );
   END COMPONENT;
   COMPONENT Datapath
   PORT (
      ALUMuxSel      : IN     std_logic ;
      ALUop          : IN     LC3b_aluop ;
      DATAIN         : IN     LC3b_word ;
      LBD_STBMux2Sel : IN     std_logic ;
      LDB_STBMuxSel  : IN     std_logic ;
      LEAMuxSel      : IN     std_logic ;
      LoadIR         : IN     std_logic ;
      LoadMAR        : IN     std_logic ;
      LoadMDR        : IN     std_logic ;
      LoadNZP        : IN     std_logic ;
      LoadPC         : IN     std_logic ;
      MARMuxSel      : IN     std_logic ;
      MDRMuxSel      : IN     std_logic ;
      PCMuxSel       : IN     LC3B_4MUX_SEL ;
      RESET_L        : IN     std_logic ;
      RFMuxSel       : IN     std_logic ;
      RegMuxSel      : IN     std_logic ;
      RegWrite       : IN     std_logic ;
      ShiftOpSel     : IN     std_logic ;
      StoreSR        : IN     std_logic ;
      Trap_JSRMuxSel : IN     std_logic ;
      clk            : IN     std_logic ;
      ADDRESS        : OUT    LC3b_word ;
      CheckN         : OUT    std_logic ;
      CheckP         : OUT    std_logic ;
      CheckZ         : OUT    std_logic ;
      DATAOUT        : OUT    LC3b_word ;
      JSR_R          : OUT    std_logic ;
      OpImmBit       : OUT    std_logic ;
      Opcode         : OUT    LC3b_opcode ;
      PCPlus2out     : OUT    LC3b_word ;
      ShiftAD        : OUT    LC3B_SHFTOP ;
      n              : OUT    std_logic ;
      p              : OUT    std_logic ;
      z              : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Memory
   PORT (
      ADDRESS   : IN     LC3b_word ;
      DATAOUT   : IN     LC3b_word ;
      MREAD_L   : IN     std_logic ;
      MWRITEH_L : IN     std_logic ;
      MWRITEL_L : IN     std_logic ;
      RESET_L   : IN     std_logic ;
      clk       : IN     std_logic ;
      DATAIN    : OUT    LC3b_word ;
      MRESP_H   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : CLKgen USE ENTITY ece411.CLKgen;
   FOR ALL : Control USE ENTITY ece411.Control;
   FOR ALL : DRAMAuditor USE ENTITY ece411.DRAMAuditor;
   FOR ALL : Datapath USE ENTITY ece411.Datapath;
   FOR ALL : Memory USE ENTITY ece411.Memory;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   CLKgen1 : CLKgen
      PORT MAP (
         clk => clk
      );
   ControlUnit : Control
      PORT MAP (
         CheckN         => CheckN,
         CheckP         => CheckP,
         CheckZ         => CheckZ,
         JSR_R          => JSR_R,
         MRESP_H        => MRESP_H,
         OpImmBit       => OpImmBit,
         Opcode         => Opcode,
         RESET_L        => RESET_L,
         START_H        => START_H,
         ShiftAD        => ShiftAD,
         clk            => clk,
         n              => n,
         p              => p,
         z              => z,
         ALUMuxSel      => ALUMuxSel,
         ALUop          => ALUop,
         LBD_STBMux2Sel => LBD_STBMux2Sel,
         LDB_STBMuxSel  => LDB_STBMuxSel,
         LEAMuxSel      => LEAMuxSel,
         LoadIR         => LoadIR,
         LoadMAR        => LoadMAR,
         LoadMDR        => LoadMDR,
         LoadNZP        => LoadNZP,
         LoadPC         => LoadPC,
         MARMuxSel      => MARMuxSel,
         MDRMuxSel      => MDRMuxSel,
         MREAD_L        => MREAD_L,
         MWRITEH_L      => MWRITEH_L,
         MWRITEL_L      => MWRITEL_L,
         PCMuxSel       => PCMuxSel,
         RFMuxSel       => RFMuxSel,
         RegMuxSel      => RegMuxSel,
         RegWrite       => RegWrite,
         ShiftOpSel     => ShiftOpSel,
         StoreSR        => StoreSR,
         Trap_JSRMuxSel => Trap_JSRMuxSel
      );
   aDRAMAuditor : DRAMAuditor
      PORT MAP (
         ADDRESS   => ADDRESS,
         MREAD_L   => MREAD_L,
         MWRITEH_L => MWRITEH_L,
         MWRITEL_L => MWRITEL_L,
         RESET_L   => RESET_L
      );
   theDatapath : Datapath
      PORT MAP (
         ALUMuxSel      => ALUMuxSel,
         ALUop          => ALUop,
         DATAIN         => DATAIN,
         LBD_STBMux2Sel => LBD_STBMux2Sel,
         LDB_STBMuxSel  => LDB_STBMuxSel,
         LEAMuxSel      => LEAMuxSel,
         LoadIR         => LoadIR,
         LoadMAR        => LoadMAR,
         LoadMDR        => LoadMDR,
         LoadNZP        => LoadNZP,
         LoadPC         => LoadPC,
         MARMuxSel      => MARMuxSel,
         MDRMuxSel      => MDRMuxSel,
         PCMuxSel       => PCMuxSel,
         RESET_L        => RESET_L,
         RFMuxSel       => RFMuxSel,
         RegMuxSel      => RegMuxSel,
         RegWrite       => RegWrite,
         ShiftOpSel     => ShiftOpSel,
         StoreSR        => StoreSR,
         Trap_JSRMuxSel => Trap_JSRMuxSel,
         clk            => clk,
         ADDRESS        => ADDRESS,
         CheckN         => CheckN,
         CheckP         => CheckP,
         CheckZ         => CheckZ,
         DATAOUT        => DATAOUT,
         JSR_R          => JSR_R,
         OpImmBit       => OpImmBit,
         Opcode         => Opcode,
         PCPlus2out     => PCPlus2out,
         ShiftAD        => ShiftAD,
         n              => n,
         p              => p,
         z              => z
      );
   DRAM : Memory
      PORT MAP (
         ADDRESS   => ADDRESS,
         DATAOUT   => DATAOUT,
         MREAD_L   => MREAD_L,
         MWRITEH_L => MWRITEH_L,
         MWRITEL_L => MWRITEL_L,
         RESET_L   => RESET_L,
         clk       => clk,
         DATAIN    => DATAIN,
         MRESP_H   => MRESP_H
      );

END struct;
