-- VHDL Entity ece411.TrapVector.generatedInstance
--
-- Created:
--          by - chachon2.ews (linux-a2.ews.illinois.edu)
--          at - 19:11:17 06/01/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2012.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;
USE ieee.std_logic_arith.all;

ENTITY TrapVector IS
   PORT( 
      clk       : IN     std_logic;
      RegMuxIn3 : OUT    LC3b_REG
   );

END TrapVector ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF TrapVector IS 
BEGIN


END generatedInstance;
